"""empty message

Revision ID: 0a2aa7857271
Revises: e056d2e93802
Create Date: 2024-04-25 16:07:58.333434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2aa7857271'
down_revision = 'e056d2e93802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail_ratio', sa.Integer(), nullable=True))
        batch_op.drop_column('exclude_domains')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exclude_domains', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('mail_ratio')

    # ### end Alembic commands ###
