"""empty message

Revision ID: b7429460df1c
Revises: 
Create Date: 2024-04-25 13:29:59.338194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7429460df1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=80), nullable=False),
    sa.Column('appium_port', sa.Integer(), nullable=False),
    sa.Column('system_port', sa.Integer(), nullable=False),
    sa.Column('key_proxy', sa.String(length=80), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=80), nullable=False),
    sa.Column('combo', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('is_login_gmail', sa.Boolean(), nullable=False),
    sa.Column('time_search_min', sa.Integer(), nullable=False),
    sa.Column('time_search_max', sa.Integer(), nullable=False),
    sa.Column('time_onpage_min', sa.Integer(), nullable=False),
    sa.Column('time_onpage_max', sa.Integer(), nullable=False),
    sa.Column('exclude_domains', sa.String(length=80), nullable=False),
    sa.Column('ads_char', sa.String(length=80), nullable=False),
    sa.Column('proxy_name', sa.String(length=80), nullable=False),
    sa.Column('isKeyword1', sa.Boolean(), nullable=False),
    sa.Column('isKeyword2', sa.Boolean(), nullable=False),
    sa.Column('isKeyword3', sa.Boolean(), nullable=False),
    sa.Column('isKeyword4', sa.Boolean(), nullable=False),
    sa.Column('isKeyword5', sa.Boolean(), nullable=False),
    sa.Column('isKeyword6', sa.Boolean(), nullable=False),
    sa.Column('isKeyword7', sa.Boolean(), nullable=False),
    sa.Column('isKeyword8', sa.Boolean(), nullable=False),
    sa.Column('isKeyword9', sa.Boolean(), nullable=False),
    sa.Column('isKeyword10', sa.Boolean(), nullable=False),
    sa.Column('isKeyword11', sa.Boolean(), nullable=False),
    sa.Column('isKeyword12', sa.Boolean(), nullable=False),
    sa.Column('isKeyword13', sa.Boolean(), nullable=False),
    sa.Column('isKeyword14', sa.Boolean(), nullable=False),
    sa.Column('isKeyword15', sa.Boolean(), nullable=False),
    sa.Column('isKeyword16', sa.Boolean(), nullable=False),
    sa.Column('isKeyword17', sa.Boolean(), nullable=False),
    sa.Column('isKeyword18', sa.Boolean(), nullable=False),
    sa.Column('isKeyword19', sa.Boolean(), nullable=False),
    sa.Column('isKeyword20', sa.Boolean(), nullable=False),
    sa.Column('isKeyword21', sa.Boolean(), nullable=False),
    sa.Column('isKeyword22', sa.Boolean(), nullable=False),
    sa.Column('isKeyword23', sa.Boolean(), nullable=False),
    sa.Column('isKeyword24', sa.Boolean(), nullable=False),
    sa.Column('isKeyword25', sa.Boolean(), nullable=False),
    sa.Column('isKeyword26', sa.Boolean(), nullable=False),
    sa.Column('isKeyword27', sa.Boolean(), nullable=False),
    sa.Column('isKeyword28', sa.Boolean(), nullable=False),
    sa.Column('isKeyword29', sa.Boolean(), nullable=False),
    sa.Column('isKeyword30', sa.Boolean(), nullable=False),
    sa.Column('isKeyword31', sa.Boolean(), nullable=False),
    sa.Column('isKeyword32', sa.Boolean(), nullable=False),
    sa.Column('isKeyword33', sa.Boolean(), nullable=False),
    sa.Column('isKeyword34', sa.Boolean(), nullable=False),
    sa.Column('isKeyword35', sa.Boolean(), nullable=False),
    sa.Column('isKeyword36', sa.Boolean(), nullable=False),
    sa.Column('isKeyword37', sa.Boolean(), nullable=False),
    sa.Column('isKeyword38', sa.Boolean(), nullable=False),
    sa.Column('isKeyword39', sa.Boolean(), nullable=False),
    sa.Column('isKeyword40', sa.Boolean(), nullable=False),
    sa.Column('isKeyword41', sa.Boolean(), nullable=False),
    sa.Column('isKeyword42', sa.Boolean(), nullable=False),
    sa.Column('isKeyword43', sa.Boolean(), nullable=False),
    sa.Column('isKeyword44', sa.Boolean(), nullable=False),
    sa.Column('isKeyword45', sa.Boolean(), nullable=False),
    sa.Column('isKeyword46', sa.Boolean(), nullable=False),
    sa.Column('isKeyword47', sa.Boolean(), nullable=False),
    sa.Column('isKeyword48', sa.Boolean(), nullable=False),
    sa.Column('isKeyword49', sa.Boolean(), nullable=False),
    sa.Column('isKeyword50', sa.Boolean(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('keywords')
    op.drop_table('devices')
    op.drop_table('profiles')
    # ### end Alembic commands ###
